import { foodItem } from "./helpers";

export const foodMenu = [
  // APPETIZERS
  foodItem("pani-puri-shots", "Pani Puri Shots", "Crisp puri shells with spiced tamarind water — a playful, luxe street-classic.", 12, "appetizers", { tags: ["Popular", "Staff Pick"], featured: true }),
  foodItem("papdi-chaat", "Papdi Chaat", "Shattered papdi, yogurt, chutneys, and sev with pomegranate sparkle.", 11, "appetizers", { tags: ["Popular"] }),
  foodItem("samosa-chaat", "Samosa Chaat", "Golden samosa crumble, tangy chutneys, and cooling yogurt.", 12, "appetizers", { tags: ["Customer Fav"] }),
  foodItem("aloo-chaat", "Aloo Chaat", "Crispy potato cubes tossed in chaat masala, lime, and fresh herbs.", 10, "appetizers"),
  foodItem("bhel-puri", "Bhel Puri", "Puffed rice, peanuts, and chutneys — light, bright, irresistible.", 10, "appetizers"),
  foodItem("sev-puri", "Sev Puri", "Mini puris stacked with potato, chutney, and fine sev.", 11, "appetizers"),
  foodItem("hot-and-sour-soup", "Hot and Sour Soup", "Silky broth with tofu, mushroom, and a balanced heat finish.", 9, "appetizers"),
  foodItem("chicken-corn-soup", "Chicken Corn Soup", "Comforting Indo-Chinese classic with sweet corn and shredded chicken.", 9, "appetizers", { tags: ["Popular"] }),
  foodItem("chicken-wings", "Chicken Wings", "Double-fried wings in honey-chipotle or garlic-parmesan glaze.", 14, "appetizers", { tags: ["Popular", "Customer Fav"], featured: true }),
  foodItem("masala-french-fries", "Masala French Fries", "Shoestring fries dusted with house masala and served with chutney aioli.", 8, "appetizers"),
  foodItem("buffalo-fries", "Buffalo Fries", "Crispy fries tossed in buffalo sauce with blue cheese drizzle.", 9, "appetizers"),
  foodItem("loaded-french-fries", "Loaded French Fries", "Fries crowned with cheese, jalapeño, and smoky chipotle crema.", 11, "appetizers", { tags: ["New"] }),
  foodItem("chicken-spring-rolls", "Chicken Spring Rolls", "Shatter-crisp rolls with seasoned chicken and sweet chili dip.", 10, "appetizers"),
  foodItem("veggie-samosas", "Veggie Samosas", "Flaky pastry filled with spiced potatoes and peas.", 8, "appetizers"),
  foodItem("samosas-chicken-beef", "Samosas (Chicken or Beef)", "Hand-folded samosas with your choice of savory filling.", 9, "appetizers"),
  foodItem("russian-chicken-cutlet", "Russian Chicken Cutlet", "Breaded cutlet with creamy filling — retro lounge favorite.", 11, "appetizers"),
  foodItem("russian-veg-cutlet", "Russian Veg Cutlet", "Vegetable cutlet with herbs and a golden crumb crust.", 10, "appetizers"),
  foodItem("tandoori-chicken-lollipop", "Tandoori Chicken Lollipop", "Charcoal-kissed drumettes with mint chutney.", 13, "appetizers", { tags: ["Staff Pick"] }),
  foodItem("hummus-pita-veggies", "Hummus with Pita & Veggies", "Silky hummus, warm pita, and crisp seasonal vegetables.", 12, "appetizers"),
  foodItem("bang-bang-shrimp", "Bang Bang Shrimp", "Crispy shrimp in creamy chili sauce with toasted sesame.", 15, "appetizers", { tags: ["New", "Staff Pick"] }),

  // SANDWICHES & ROLLS
  foodItem("chicken-club-sandwich", "Chicken Club Sandwich", "Triple-decker with turkey, bacon, avocado, and gold-dusted fries.", 15, "sandwiches"),
  foodItem("veggie-chutney-sandwich", "Veggie Chutney Sandwich", "Garden vegetables, green chutney, and soft brioche.", 12, "sandwiches"),
  foodItem("sheesh-burger", "Sheesh Burger", "Smash patty, truffle aioli, caramelized onion, brioche bun.", 16, "sandwiches", { tags: ["Popular", "Staff Pick"], featured: true }),
  foodItem("sheesh-smash-burger", "Sheesh Smash Burger", "Double smash, American cheese, house sauce, pickles.", 18, "sandwiches", { tags: ["Popular"] }),
  foodItem("chicken-philly", "Chicken Philly", "Sliced chicken, peppers, and melted provolone on a toasted roll.", 15, "sandwiches"),
  foodItem("beef-philly", "Beef Philly", "Tender beef, onions, and cheese — classic late-night luxury.", 16, "sandwiches"),
  foodItem("bun-kabob", "Bun Kabob", "Spiced patty, chutney, and onion on a buttered bun.", 12, "sandwiches", { tags: ["Customer Fav"] }),
  foodItem("mani-mia-kay-bun-kabob", "Mani Mia Kay Bun Kabob", "Signature Sheesh patty with secret house chutney blend.", 13, "sandwiches", { tags: ["Staff Pick"] }),
  foodItem("chicken-paratha-roll", "Chicken Paratha Roll", "Tandoori chicken wrapped in flaky paratha with raita.", 14, "sandwiches", { tags: ["Popular"] }),
  foodItem("beef-paratha-roll", "Beef Paratha Roll", "Spiced beef keema rolled in buttery paratha.", 15, "sandwiches"),
  foodItem("chicken-bihari-paratha-roll", "Chicken Bihari Kabab Paratha Roll", "Smoky Bihari chicken with onions and green chutney.", 15, "sandwiches"),
  foodItem("beef-bihari-paratha-roll", "Beef Bihari Kabab Paratha Roll", "Charcoal Bihari beef wrapped warm in paratha.", 16, "sandwiches"),
  foodItem("chicken-seekh-paratha-roll", "Chicken Seekh Kabab Paratha Roll", "Juicy seekh with fresh herbs and lime.", 14, "sandwiches"),
  foodItem("beef-seekh-paratha-roll", "Beef Seekh Kabab Paratha Roll", "Bold beef seekh, onions, and house masala.", 15, "sandwiches"),
  foodItem("chicken-tikka-boti-paratha-roll", "Chicken Tikka Boti Paratha Roll", "Tikka boti, peppers, and creamy sauce in paratha.", 15, "sandwiches"),
  foodItem("gola-kabob-roll", "Gola Kabob Roll", "Spiced gola kabob with tangy chutney — street icon, elevated.", 14, "sandwiches", { tags: ["Customer Fav"] }),

  // BBQ
  foodItem("goat-chops", "Goat Chops", "Herb-marinated chops grilled over open flame with mint yogurt.", 32, "bbq", { tags: ["Staff Pick"] }),
  foodItem("sheesh-bbq-platter", "Sheesh BBQ Platter", "Chicken tikka, seekh kebab, and lamb with house chutneys.", 42, "bbq", { tags: ["Popular", "Staff Pick"], featured: true, layout: "wide" }),
  foodItem("seekh-kabab", "Seekh Kabab (Beef or Chicken)", "Hand-pressed seekh, charcoal aroma, served sizzling.", 18, "bbq", { tags: ["Popular"] }),
  foodItem("boneless-chicken-tikka", "Boneless Chicken Tikka Pieces", "Creamy marinade, tandoor char, lemon finish.", 17, "bbq"),
  foodItem("chicken-tikka-leg", "Chicken Tikka Leg", "Whole leg marinated overnight, flame-kissed.", 16, "bbq"),
  foodItem("chapli-kabob-platter", "Chapli Kabob Platter", "Peshawari-style patties with naan and salad.", 20, "bbq", { tags: ["Customer Fav"] }),
  foodItem("chicken-shahi-kabob", "Chicken Shahi Kabob", "Royal marinade with cardamom and cream — regal plate.", 19, "bbq"),
  foodItem("bihari-kabab", "Beef Bihari or Chicken Bihari", "Signature Bihari spice blend, served with naan.", 18, "bbq", { tags: ["Popular"] }),

  // DESI
  foodItem("magaz-nihari", "Magaz Nihari", "Slow-braised brain nihari in royal masala with ginger garnish.", 18, "desi", { tags: ["Staff Pick", "Popular"], featured: true }),
  foodItem("beef-nihari", "Beef Nihari", "Overnight-stewed beef shank finished with desi ghee.", 20, "desi", { tags: ["Popular", "Customer Fav"], featured: true }),
  foodItem("special-magaz-fry", "Special Magaz Fry", "Pan-fried magaz with aromatics — bold, rich, indulgent.", 19, "desi", { tags: ["Staff Pick"] }),
  foodItem("beef-haleem", "Beef Haleem", "Silky lentil-wheat stew with shredded beef and fried onion.", 17, "desi"),
  foodItem("chicken-karahi", "Chicken Karahi", "Wok-fired chicken in tomato, ginger, and green chili.", 22, "desi", { tags: ["Popular"], featured: true }),
  foodItem("special-dhaba-goat-karahi", "Special Dhaba Goat Karahi", "Rustic goat karahi with whole spices — dhaba soul, lounge polish.", 26, "desi", { tags: ["Staff Pick"] }),
  foodItem("goat-biryani", "Goat Biryani", "Layered dum biryani with tender goat and fried onions.", 23, "desi", { tags: ["Popular"] }),
  foodItem("chicken-biryani", "Chicken Biryani", "Fragrant basmati, saffron, and marinated chicken.", 19, "desi", { tags: ["Customer Fav", "Popular"] }),
  foodItem("chicken-keema-paratha", "Chicken Keema & Paratha", "Spiced minced chicken with buttery paratha.", 16, "desi"),
  foodItem("beef-keema-paratha", "Beef Keema & Paratha", "Rich beef keema paired with flaky paratha.", 17, "desi"),
  foodItem("goat-keema-paratha", "Goat Keema & Paratha", "Slow-cooked goat keema — hearty and aromatic.", 18, "desi"),
  foodItem("butter-chicken-plate", "Butter Chicken Plate", "Tandoori chicken in velvet makhani with naan.", 19, "desi", { tags: ["Popular"], featured: true }),
  foodItem("butter-paneer-plate", "Butter Paneer Plate", "Paneer tikka in creamy tomato-butter sauce.", 17, "desi"),
  foodItem("butter-chicken-pasta", "Butter Chicken Pasta", "Fusion penne tossed in makhani cream sauce.", 18, "desi", { tags: ["New"] }),
  foodItem("butter-paneer-pasta", "Butter Paneer Pasta", "Paneer and pasta in rich butter masala.", 17, "desi", { tags: ["New"] }),
  foodItem("halwa-puri-choley", "Halwa Puri Choley", "Weekend-style breakfast plate — sweet, savory, nostalgic.", 15, "desi"),
  foodItem("omelet-paratha", "Omelet & Paratha", "Masala omelet with paratha and chutney.", 12, "desi"),
  foodItem("veggie-tawa-pulao", "Veggie Tawa Pulao", "Smoky tawa-fried rice with seasonal vegetables.", 14, "desi"),
  foodItem("sizzling-gajjar-halwa", "Sizzling Gajjar Halwa", "Carrot halwa served hot on a sizzler with nuts.", 11, "desi", { tags: ["Customer Fav"] }),

  // CHINESE
  foodItem("sweet-sour-chicken", "Sweet & Sour Chicken", "Crispy chicken in glossy sweet-tangy glaze.", 16, "chinese", { tags: ["Popular"] }),
  foodItem("chilli-beef", "Chilli Beef", "Wok-tossed beef with dry chilies and scallions.", 18, "chinese"),
  foodItem("garlic-chicken", "Garlic Chicken", "Golden chicken in aromatic garlic sauce.", 16, "chinese"),
  foodItem("shanghai-shrimps", "Shanghai Shrimps", "Crispy shrimp in spicy Shanghai-style sauce.", 19, "chinese", { tags: ["Staff Pick"] }),
  foodItem("mongolian-beef", "Mongolian Beef", "Tender beef with soy, garlic, and scallion.", 18, "chinese"),
  foodItem("black-pepper-beef", "Black Pepper Beef", "Bold pepper crust with velvety onion gravy.", 18, "chinese"),
  foodItem("fd-sizzler-chicken", "FD Sizzler (Chicken)", "Sizzling chicken with peppers on a hot plate.", 20, "chinese", { tags: ["New"] }),
];
